name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/common.yml

  deploy-backend:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy backend
        run: kubectl set image deployment/backend-deployment backend=my-docker-repo/backend:$GITHUB_SHA

  deploy-frontend:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy frontend
        run: kubectl set image deployment/frontend-deployment frontend=my-docker-repo/frontend:$GITHUB_SHA
